/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.qapsoft.io.BinaryColumn
import com.qapsoft.io.BinaryTableData
import com.qapsoft.io.BinaryTableHeader
import com.qapsoft.io.setValue
import java.io.File

fun main() {

    val table = BinaryTableData(
        header = BinaryTableHeader(
            1000,
            columns = listOf(
                BinaryColumn.Int("_id"),
                BinaryColumn.Int("first_name"),
                BinaryColumn.Int("last_name"),
                )

        ),
        file = File("c:/52/a.txt")
    )

}
